* pg-install script literate programming

Once it's done, let's move the code of =pg-install= and the most salient parts
of this file as into an /OrgMode Literate Programming Document/!

In the meantime, we're pooling issues and commentary here.  It's messy!

** Issues

- Prune these issues before this script is released!

*** Caveats: Should we issue some caveats at startup?
- and require and acknowledgment from the user before proceeding as before?
*** Issue: Account running this script
It would be much nicer if this script were run by an unprivileged script rather than root!
Possible solutions:
- Break it up into three scripts and a common sourced module
      - Common Module - defines functions and sorts global parameters
            - Each of the others processes the arguments again, with the same code
      - Main tiny script runs as root or as someone with sudo privileges
      - Bin script runs as =bin=
      - Pg script runs as =postgres=

*** Issue: Build-Depends

Figuring out build-dependencies, including those needed for the extra features
we're adding, is a pain. We've always done it by hand before. We're probably
still going to have to do it mostly by hand, but let's record all of the
dependencies on our various platforms and see if we can at least document them
and hopefully semi or fully automate their installation! Notes on Proposed
Solution with Debian-based Linux:

- See [[https://www.guyrutenberg.com/2017/09/23/use-mk-build-deps-instead-of-apt-get-build-dep][prefer mk-build-deps]]
#+begin_src shell
# Basics:
apt install -y build-essential
# Maybe:
apt install -y autotools-dev dpkg-dev devscripts
Get the postgresql source package
apt-get build-dep postgresql
# or follow the advice at
$ mk-build-deps PKGNAME --install --root-cmd sudo --remove
# and install that
# Install all the other things:
apt install xsltproc libxslt1.1 libxslt1-dev # check version
apt install tcl tcl8.6-dev tcllib tclxml # check version
any libxml2 packages needed??
apt install tcl8.6-tdbc tcl8.6-tdbc-postgres
# Proposed Solution with Mac: ???
# Solutions for other platforms: ???
#+end_src

Some build dependencies
- standard Posix development tools for C programming:
      - cc, cpp, make, pkg-config, etc.
      - bison, flex
- additional Posix tools
      - awk or gawk
      - tar
      - perl
      - sed, grep, egrep
- additional libraries
      - pthreads or acceptable alternative
      - XML
            - libxml2
            - xsltproc, libxslt
      - unicode
- optional desirable things
      - readline or alternative
      - Tcl
      - lz compression: zlib, liblz
      - DocBook XML - for making the online documentation

*** Issue: Postgres Account uncomfortable from command shell
Proposed solution:
Make sure the account exists with a nice shell.
- Maybe take the shell from the real-user-id?
- And/or make it yet another option
Copy over a nice =skel=
- start with =/etc/skel=
Create a =pg_skel= (where?) with
 - =.profile= =.sh.d/*= =.guix-profile= =.config/guix=
 - what goes in =.sh.d= and what else do we want?

Consider using Wicci paths script to simplify Profile!

** Error Detection and Tracing

*** Error Management

#+begin_src shell
  set -u  # expansion of undefined variable is an error
  set -e  # error of a complete command aborts script
  # skip pipefail because we're usually piping to a logging sink
  set -o pipefail                 # exit code from last component failing
  set -v                          # echo commands before expansion
  set -vx                         # echo commands before execution
#+end_src

*** Reporting Convenience Functions

This all got revamped!

** Bash Bug(s) and Infelicities

When I did a =declare -r from= on global parameter =from= it caused errors
in modifying local parameter =from=.

=type -p type=
- gives the empty string as expected
- gives success NOT as expected!
